### PR TITLE
minitest-rails 0.9.2, shoulda-matchers 2.0.0, and deprecation updates

### PR DESCRIPTION
**Pull request by kitop**
I've updated 2 outdated dependencies.
`minitest-rails` is now on `0.9.2` and `shoulda-matchers` in `2.0.0`.

Tests are all passing, but had to change a matcher (`respond_with_content_type`) because it was removed on `shoulda-matchers` 2.0.0. It's now using `respond_with` and test descriptions were updated.

A test for models was also added. I believe because of a side effect of `minitest-rails` 0.9.2 some matchers now need to be more explicit.
`ActiveSupport::TestCase` now includes `MiniTest::Spec::DSL`, and instead of inheriting from `MiniTest::Spec` it inherits from `MiniTest::Unit::TestCase`
`minitest-matchers` defines `self.must`, etc on `MiniTest::Spec`, and I believe there's the problem.

I'll try to keep investigating, but everything else seems to be working OK!

Tested it on Ruby 1.9, and Ruby 2.0 with Rails 4.

### CODE REVIEW

**Comment by marnen** [comment]
This doesn't appear to be working for me with Ruby 2 and Rails 4. Anytime I try to use it, I get `undefined method 'reflect_on_association'`. Help?

**Comment by marnen** [comment]
Further info: `Post.new.must have_many :comments` works. It's the recommended

```
subject { Post.new }
it { must have_many :comments }
```

that doesn't work.

**Comment by kitop** [comment]
This is kinda outdated, but should be working. I was using it in production.
What versions of shoulda-matchers, minitest-matchers, and minitest-rails are you using? (Can you check the Gemfile.lock?)

Will give a it a look.

**Comment by marnen** [comment]
I'm using shoulda-matchers 2.1.0, minitest-matchers 1.3.0, and minitest-rails 0.9.2.

**Comment by phlipper** [comment]
@kitop, @marnen, we have some work underway to bring this up-to-date with the latest versions of `minitest-rails` and `shoulda-matchers`, but there have been a few blockers with some other associated gems that have kept things moving a little slowly. 

Minitest 5.x and Shoulda-Matchers 2.x both brought some large changes and backwards incompatibility. We have made some progress getting PRs accepted on related projects, and we're waiting on just a few more, and then we should be able to finish getting this update out the door.

Thanks for the interest!

**Comment by kitop** [comment]
@phlipper thanks for the update!!

Need any particular help? glad to help!

**Comment by GeoffTidey** [comment]
Hey, just to confirm the @kitop branch is working for me 

```
gem 'minitest-rails-shoulda', :github => "kitop/minitest-rails-shoulda", :branch => 'minitest-rails-0.9.2-updates'
```

without using subject as suggested here https://github.com/newleaders/minitest-rails-shoulda/pull/10#issuecomment-20746411 by @marnen 

using ruby 1.9.2-p320 with shoulda-matchers 2.1.0, minitest-matchers 1.3.0, and minitest-rails 0.9.2.

cheers all that are working on this update  :+1:  This thread has made my Friday slightly better :beers:

**Comment by yourtallness** [comment]
It would be nice to have this released.

**Comment by marnen** [comment]
At this point this pull request has been open for more than a year. What's the problem? Can I help?

**Comment by marnen** [comment]
Closed without a release or a comment?

**Comment by kitop** [comment]
Sorry for not commenting.
It's been over 4 years. Those dependencies are now well outdated too. Feel free to reopen and take care of it if you see fit.

**Comment by marnen** [comment]
@kitop Yeah, good point. :P

**Pull request closed without merging**
